name: Deploy MultiK8s
on:
  push:
    branches:
      - master
 
env:
  SHA: $(git rev-parse HEAD)
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t abhinayreddydocker/react-test -f ./complex-gh-copy/client/Dockerfile.dev ./complex-gh-copy/client
          docker run -e CI=true abhinayreddydocker/react-test npm test
      - name: Set Service Key
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
 
      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: multi-k8s-410220
 
      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker
 
      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: asia-south1-a
 
      - name: Build
        run: |-
          docker build -t abhinayreddydocker/multi-client-k8s-gh:latest -t abhinayreddydocker/multi-client-k8s-gh:${{ env.SHA }} -f /complex-gh-copy/client/Dockerfile /complex-gh-copy/client
          docker build -t abhinayreddydocker/multi-server-k8s-pgfix-gh:latest -t cabhinayreddydocker/multi-server-k8s-pgfix-gh:${{ env.SHA }} -f /complex-gh-copy/server/Dockerfile /complex-gh-copy/server
          docker build -t abhinayreddydocker/multi-worker-k8s-gh:latest -t abhinayreddydocker/multi-worker-k8s-gh:${{ env.SHA }} -f /complex-gh-copy/worker/Dockerfile /complex-gh-copy/worker
 
      - name: Push
        run: |-
          docker push abhinayreddydocker/multi-client-k8s-gh:latest
          docker push abhinayreddydocker/multi-server-k8s-pgfix-gh:latest
          docker push abhinayreddydocker/multi-worker-k8s-gh:latest
 
          docker push abhinayreddydocker/multi-client-k8s-gh:${{ env.SHA }}
          docker push abhinayreddydocker/multi-server-k8s-pgfix-gh:${{ env.SHA }}
          docker push abhinayreddydocker/multi-worker-k8s-gh:${{ env.SHA }}
 
      - name: Apply
        run: |-
          kubectl apply -f /simplek8s
          kubectl set image deployments/server-deployment server=abhinayreddydocker/multi-server-k8s-pgfix-gh:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=abhinayreddydocker/multi-client-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=abhinayreddydocker/multi-worker-k8s-gh:${{ env.SHA }}
